# CMake generated Testfile for 
# Source directory: /home/skiidk/pemu/plugins/Triton/src/testers
# Build directory: /home/skiidk/pemu/plugins/Triton/src/testers
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
ADD_TEST(PinToolCheckUnsupportedSemantic "sh" "-c" "/home/skiidk/pemu/plugins/Triton/triton /home/skiidk/pemu/plugins/Triton/src/testers/pin/unsuported_semantics.py /home/skiidk/pemu/plugins/Triton/src/samples/ir_test_suite/ir | tee /tmp/tester_triton_xxx && ! grep -nr KO /tmp/tester_triton_xxx")
ADD_TEST(PinToolCheckSemantic "sh" "-c" "/home/skiidk/pemu/plugins/Triton/triton /home/skiidk/pemu/plugins/Triton/src/testers/pin/check_semantics.py /home/skiidk/pemu/plugins/Triton/src/samples/ir_test_suite/ir | tee /tmp/tester_triton_xxx && ! grep -nr KO /tmp/tester_triton_xxx")
ADD_TEST(PinToolCheckSemanticQemu "sh" "-c" "/home/skiidk/pemu/plugins/Triton/triton /home/skiidk/pemu/plugins/Triton/src/testers/pin/qemu-test-x86_64.py /home/skiidk/pemu/plugins/Triton/src/samples/ir_test_suite/qemu-test-x86_64| tee /tmp/tester_triton_xxx && ! grep -nr KO /tmp/tester_triton_xxx")
ADD_TEST(PinToolBlackList "sh" "-c" "/home/skiidk/pemu/plugins/Triton/triton /home/skiidk/pemu/plugins/Triton/src/examples/pin/blacklist.py /home/skiidk/pemu/plugins/Triton/src/samples/crackmes/crackme_xor a | tee /tmp/tester_triton_xxx && grep -nr fail /tmp/tester_triton_xxx")
ADD_TEST(PinToolCallBackConcreteNeeds "sh" "-c" "/home/skiidk/pemu/plugins/Triton/triton /home/skiidk/pemu/plugins/Triton/src/examples/pin/callback_concrete_needs.py /home/skiidk/pemu/plugins/Triton/src/samples/ir_test_suite/ir | tee /tmp/tester_triton_xxx && grep -nr \"Need concrete register value\" /tmp/tester_triton_xxx")
ADD_TEST(PinToolCallBackImage "sh" "-c" "/home/skiidk/pemu/plugins/Triton/triton /home/skiidk/pemu/plugins/Triton/src/examples/pin/callback_image.py /home/skiidk/pemu/plugins/Triton/src/samples/ir_test_suite/ir | tee /tmp/tester_triton_xxx && grep -nr \"Image size:\" /tmp/tester_triton_xxx")
ADD_TEST(PinToolCallBackRoutine "sh" "-c" "/home/skiidk/pemu/plugins/Triton/triton /home/skiidk/pemu/plugins/Triton/src/examples/pin/callback_routine.py /home/skiidk/pemu/plugins/Triton/src/samples/vulns/testSuite | tee /tmp/tester_triton_xxx && grep -nr malloc /tmp/tester_triton_xxx")
ADD_TEST(PinToolCallBackSyscall "sh" "-c" "/home/skiidk/pemu/plugins/Triton/triton /home/skiidk/pemu/plugins/Triton/src/examples/pin/callback_syscall.py /home/skiidk/pemu/plugins/Triton/src/samples/crackmes/crackme_xor a | tee /tmp/tester_triton_xxx && grep -nr fail /tmp/tester_triton_xxx")
ADD_TEST(PinToolCallBackSignals "sh" "-c" "/home/skiidk/pemu/plugins/Triton/triton /home/skiidk/pemu/plugins/Triton/src/examples/pin/callback_signals.py /home/skiidk/pemu/plugins/Triton/src/samples/others/signals | tee /tmp/tester_triton_xxx && grep -nr UNSET /tmp/tester_triton_xxx")
ADD_TEST(PinToolCountInst "sh" "-c" "/home/skiidk/pemu/plugins/Triton/triton /home/skiidk/pemu/plugins/Triton/src/examples/pin/count_inst.py /home/skiidk/pemu/plugins/Triton/src/samples/crackmes/crackme_hash aaaaa | tee /tmp/tester_triton_xxx && grep -nr \"Instruction count\" /tmp/tester_triton_xxx")
ADD_TEST(PinToolCrackMeHashCollision "sh" "-c" "/home/skiidk/pemu/plugins/Triton/triton /home/skiidk/pemu/plugins/Triton/src/examples/pin/crackme_hash_collision.py /home/skiidk/pemu/plugins/Triton/src/samples/crackmes/crackme_hash aaaaa | tee /tmp/tester_triton_xxx && grep -nr fail /tmp/tester_triton_xxx")
ADD_TEST(PinToolInjectModelWithSnapShot "sh" "-c" "/home/skiidk/pemu/plugins/Triton/triton /home/skiidk/pemu/plugins/Triton/src/examples/pin/inject_model_with_snapshot.py /home/skiidk/pemu/plugins/Triton/src/samples/crackmes/crackme_xor a | tee /tmp/tester_triton_xxx && grep -nr Win /tmp/tester_triton_xxx")
ADD_TEST(PinToolIr "sh" "-c" "/home/skiidk/pemu/plugins/Triton/triton /home/skiidk/pemu/plugins/Triton/src/examples/pin/ir.py /home/skiidk/pemu/plugins/Triton/src/samples/crackmes/crackme_xor a | tee /tmp/tester_triton_xxx && grep -nr \"syscall\" /tmp/tester_triton_xxx")
ADD_TEST(PinToolMainAndStack "sh" "-c" "/home/skiidk/pemu/plugins/Triton/triton /home/skiidk/pemu/plugins/Triton/src/examples/pin/looking_for_stack_base_and_main_addr.py /home/skiidk/pemu/plugins/Triton/src/samples/crackmes/crackme_xor a | tee /tmp/tester_triton_xxx && grep -nr 4005b3 /tmp/tester_triton_xxx")
ADD_TEST(PinToolPathConstraints "sh" "-c" "/home/skiidk/pemu/plugins/Triton/triton /home/skiidk/pemu/plugins/Triton/src/examples/pin/path_constraints.py /home/skiidk/pemu/plugins/Triton/src/samples/crackmes/crackme_xor eli | tee /tmp/tester_triton_xxx && grep -nr \"SymVar_3:8 = 0x74 (t)\" /tmp/tester_triton_xxx")
ADD_TEST(PinToolRuntimeMemoryTainting "sh" "-c" "/home/skiidk/pemu/plugins/Triton/triton /home/skiidk/pemu/plugins/Triton/src/examples/pin/runtime_memory_tainting.py /home/skiidk/pemu/plugins/Triton/src/samples/crackmes/crackme_xor a | tee /tmp/tester_triton_xxx && grep -nr fail /tmp/tester_triton_xxx")
ADD_TEST(PinToolRuntimeRegisterModification "sh" "-c" "/home/skiidk/pemu/plugins/Triton/triton /home/skiidk/pemu/plugins/Triton/src/examples/pin/runtime_register_modification.py /home/skiidk/pemu/plugins/Triton/src/samples/crackmes/crackme_xor a | tee /tmp/tester_triton_xxx && grep -nr Win /tmp/tester_triton_xxx")
ADD_TEST(PinToolStrLen "sh" "-c" "/home/skiidk/pemu/plugins/Triton/triton /home/skiidk/pemu/plugins/Triton/src/examples/pin/strlen.py /home/skiidk/pemu/plugins/Triton/src/samples/others/strlen 1 | tee /tmp/tester_triton_xxx && grep -nr pointer /tmp/tester_triton_xxx")
ADD_TEST(PinToolSymOnlyOnTainted "sh" "-c" "/home/skiidk/pemu/plugins/Triton/triton /home/skiidk/pemu/plugins/Triton/src/examples/pin/sym_only_on_tainted.py /home/skiidk/pemu/plugins/Triton/src/samples/crackmes/crackme_xor a | tee /tmp/tester_triton_xxx && grep -nr fail /tmp/tester_triton_xxx")
ADD_TEST(PinToolReadFromFile "sh" "-c" "/home/skiidk/pemu/plugins/Triton/triton /home/skiidk/pemu/plugins/Triton/src/examples/pin/symbolize_input_file.py /home/skiidk/pemu/plugins/Triton/src/samples/others/read_from_file | tee /tmp/tester_triton_xxx && grep -nr Model /tmp/tester_triton_xxx")
ADD_TEST(PinToolTraceInst "sh" "-c" "/home/skiidk/pemu/plugins/Triton/triton /home/skiidk/pemu/plugins/Triton/src/examples/pin/trace_inst.py /home/skiidk/pemu/plugins/Triton/src/samples/crackmes/crackme_xor a | tee /tmp/tester_triton_xxx && grep -nr syscall /tmp/tester_triton_xxx")
ADD_TEST(UnicornAArch64Semantics "sh" "-c" "/usr/bin/python2.7 /home/skiidk/pemu/plugins/Triton/src/testers/aarch64/unicorn_test_aarch64.py")
ADD_TEST(UnicornX86Semantics "sh" "-c" "/usr/bin/python2.7 /home/skiidk/pemu/plugins/Triton/src/testers/x86/unicorn_test_x86.py")
ADD_TEST(UnicornARM32Semantics1 "sh" "-c" "/usr/bin/python2.7 /home/skiidk/pemu/plugins/Triton/src/testers/arm32/unicorn_test_arm32_branch_arm_1.py")
ADD_TEST(UnicornARM32Semantics2 "sh" "-c" "/usr/bin/python2.7 /home/skiidk/pemu/plugins/Triton/src/testers/arm32/unicorn_test_arm32_branch_arm_2.py")
ADD_TEST(UnicornARM32Semantics3 "sh" "-c" "/usr/bin/python2.7 /home/skiidk/pemu/plugins/Triton/src/testers/arm32/unicorn_test_arm32_branch_pc_arm_1.py")
ADD_TEST(UnicornARM32Semantics4 "sh" "-c" "/usr/bin/python2.7 /home/skiidk/pemu/plugins/Triton/src/testers/arm32/unicorn_test_arm32_branch_pc_arm_2.py")
ADD_TEST(UnicornARM32Semantics5 "sh" "-c" "/usr/bin/python2.7 /home/skiidk/pemu/plugins/Triton/src/testers/arm32/unicorn_test_arm32_branch_thumb_1.py")
ADD_TEST(UnicornARM32Semantics6 "sh" "-c" "/usr/bin/python2.7 /home/skiidk/pemu/plugins/Triton/src/testers/arm32/unicorn_test_arm32_branch_thumb_2.py")
ADD_TEST(UnicornARM32Semantics7 "sh" "-c" "/usr/bin/python2.7 /home/skiidk/pemu/plugins/Triton/src/testers/arm32/unicorn_test_arm32_data_arm.py")
ADD_TEST(UnicornARM32Semantics8 "sh" "-c" "/usr/bin/python2.7 /home/skiidk/pemu/plugins/Triton/src/testers/arm32/unicorn_test_arm32_data_thumb.py")
ADD_TEST(UnicornARM32Semantics9 "sh" "-c" "/usr/bin/python2.7 /home/skiidk/pemu/plugins/Triton/src/testers/arm32/unicorn_test_arm32_interworking_arm.py")
ADD_TEST(UnicornARM32Semantics10 "sh" "-c" "/usr/bin/python2.7 /home/skiidk/pemu/plugins/Triton/src/testers/arm32/unicorn_test_arm32_interworking_thumb.py")
ADD_TEST(UnicornARM32Semantics11 "sh" "-c" "/usr/bin/python2.7 /home/skiidk/pemu/plugins/Triton/src/testers/arm32/unicorn_test_arm32_loadstore_arm_1.py")
ADD_TEST(UnicornARM32Semantics12 "sh" "-c" "/usr/bin/python2.7 /home/skiidk/pemu/plugins/Triton/src/testers/arm32/unicorn_test_arm32_loadstore_arm_2.py")
ADD_TEST(UnicornARM32Semantics13 "sh" "-c" "/usr/bin/python2.7 /home/skiidk/pemu/plugins/Triton/src/testers/arm32/unicorn_test_arm32_loadstore_arm_3.py")
ADD_TEST(UnicornARM32Semantics14 "sh" "-c" "/usr/bin/python2.7 /home/skiidk/pemu/plugins/Triton/src/testers/arm32/unicorn_test_arm32_loadstore_arm_4.py")
ADD_TEST(UnicornARM32Semantics15 "sh" "-c" "/usr/bin/python2.7 /home/skiidk/pemu/plugins/Triton/src/testers/arm32/unicorn_test_arm32_loadstore_thumb_1.py")
ADD_TEST(UnicornARM32Semantics16 "sh" "-c" "/usr/bin/python2.7 /home/skiidk/pemu/plugins/Triton/src/testers/arm32/unicorn_test_arm32_loadstore_thumb_2.py")
ADD_TEST(UnicornARM32Semantics17 "sh" "-c" "/usr/bin/python2.7 /home/skiidk/pemu/plugins/Triton/src/testers/arm32/unicorn_test_arm32_loadstore_thumb_3.py")
ADD_TEST(UnicornARM32Semantics18 "sh" "-c" "/usr/bin/python2.7 /home/skiidk/pemu/plugins/Triton/src/testers/arm32/crypto_test/crypto_test-nothumb-O0-run.py")
ADD_TEST(UnicornARM32Semantics19 "sh" "-c" "/usr/bin/python2.7 /home/skiidk/pemu/plugins/Triton/src/testers/arm32/crypto_test/crypto_test-nothumb-O1-run.py")
ADD_TEST(UnicornARM32Semantics20 "sh" "-c" "/usr/bin/python2.7 /home/skiidk/pemu/plugins/Triton/src/testers/arm32/crypto_test/crypto_test-nothumb-O2-run.py")
ADD_TEST(UnicornARM32Semantics21 "sh" "-c" "/usr/bin/python2.7 /home/skiidk/pemu/plugins/Triton/src/testers/arm32/crypto_test/crypto_test-nothumb-O3-run.py")
ADD_TEST(UnicornARM32Semantics22 "sh" "-c" "/usr/bin/python2.7 /home/skiidk/pemu/plugins/Triton/src/testers/arm32/crypto_test/crypto_test-nothumb-Os-run.py")
ADD_TEST(UnicornARM32Semantics23 "sh" "-c" "/usr/bin/python2.7 /home/skiidk/pemu/plugins/Triton/src/testers/arm32/crypto_test/crypto_test-nothumb-Oz-run.py")
ADD_TEST(UnicornARM32Semantics24 "sh" "-c" "/usr/bin/python2.7 /home/skiidk/pemu/plugins/Triton/src/testers/arm32/crypto_test/crypto_test-thumb-O0-run.py")
ADD_TEST(UnicornARM32Semantics25 "sh" "-c" "/usr/bin/python2.7 /home/skiidk/pemu/plugins/Triton/src/testers/arm32/crypto_test/crypto_test-thumb-O1-run.py")
ADD_TEST(UnicornARM32Semantics26 "sh" "-c" "/usr/bin/python2.7 /home/skiidk/pemu/plugins/Triton/src/testers/arm32/crypto_test/crypto_test-thumb-O2-run.py")
ADD_TEST(UnicornARM32Semantics27 "sh" "-c" "/usr/bin/python2.7 /home/skiidk/pemu/plugins/Triton/src/testers/arm32/crypto_test/crypto_test-thumb-O3-run.py")
ADD_TEST(UnicornARM32Semantics28 "sh" "-c" "/usr/bin/python2.7 /home/skiidk/pemu/plugins/Triton/src/testers/arm32/crypto_test/crypto_test-thumb-Os-run.py")
ADD_TEST(UnicornARM32Semantics29 "sh" "-c" "/usr/bin/python2.7 /home/skiidk/pemu/plugins/Triton/src/testers/arm32/crypto_test/crypto_test-thumb-Oz-run.py")
